/* eslint-disable @typescript-eslint/no-explicit-any */
import { useEffect, useMemo, useState } from 'react';
import { Clock3, Phone, PhoneForwarded, Target } from 'lucide-react';
import { EmptyState, MetricCard, PageHeader, PageLoading, SectionCard, StatusBadge } from '../components/operations/ProductUI';
import { Campaign, CampaignStats, CallStats, Lead, getCallStats, getCampaignLeads, getCampaignStats, getCampaigns, isAnswered, isQualified, sumValues } from '../services/operationsApi';

type CampaignView = { campaign: Campaign; stats: CampaignStats; leads: Lead[] };
const pct = (a: number, b: number) => b ? `${Math.round(a / b * 100)}%` : '0%';
export default function AnalyticsPage() {
    const [stats, setStats] = useState<CallStats | null>(null); const [campaigns, setCampaigns] = useState<CampaignView[]>([]); const [loading, setLoading] = useState(true); const [error, setError] = useState('');
    useEffect(() => { (async () => { try { const list = await getCampaigns(); const [callStats, views] = await Promise.all([getCallStats(), Promise.all(list.map(async campaign => ({ campaign, stats: await getCampaignStats(campaign.id), leads: await getCampaignLeads(campaign) })))]); setStats(callStats); setCampaigns(views); } catch (e: any) { setError(e?.message || 'Unable to load analytics.'); } finally { setLoading(false); } })(); }, []);
    const totals = useMemo(() => { const leads = campaigns.flatMap(c => c.leads); const attempts = campaigns.reduce((n, c) => n + sumValues(c.stats.attempt_outcomes), 0); const answered = leads.filter(isAnswered).length; const qualified = leads.filter(isQualified).length; const transfers = leads.filter(l => Boolean(l.last_transfer_successful)).length; return { attempts, answered, qualified, transfers }; }, [campaigns]);
    if (loading) return <PageLoading label="Loading analytics" />;
    return <div className="space-y-8"><PageHeader eyebrow="Overview" title="Analytics" description="Campaign and call-history analysis generated from persisted operational data." />{error && <div className="rounded-lg border border-red-500/20 bg-red-500/10 p-4 text-sm text-red-700">{error}</div>}
        <div className="grid gap-4 md:grid-cols-2 xl:grid-cols-4"><MetricCard label="Total calls" value={stats?.total_calls || totals.attempts} icon={Phone} /><MetricCard label="Answer rate" value={pct(totals.answered, totals.attempts)} icon={Phone} /><MetricCard label="Qualification rate" value={pct(totals.qualified, totals.answered)} icon={Target} tone="success" /><MetricCard label="Transfer rate" value={pct(totals.transfers, totals.qualified)} icon={PhoneForwarded} tone="success" /></div>
        <div className="grid gap-6 xl:grid-cols-2"><SectionCard title="Calls over time" description="Persisted call history by day">{!stats?.calls_per_day?.length ? <EmptyState title="No call trend yet" description="Daily call volume appears after calls are recorded." /> : <div className="space-y-4 p-5">{stats.calls_per_day.slice(-14).map(day => { const max = Math.max(...stats.calls_per_day.map(d => d.count), 1); return <div key={day.date} className="grid grid-cols-[88px_1fr_38px] items-center gap-3 text-sm"><span className="text-muted-foreground">{new Date(day.date).toLocaleDateString([], { month: 'short', day: 'numeric' })}</span><div className="h-2 rounded-full bg-muted"><div className="h-full rounded-full bg-primary" style={{ width: `${day.count / max * 100}%` }} /></div><span className="text-right font-medium tabular-nums">{day.count}</span></div>})}</div>}</SectionCard>
            <SectionCard title="Outcomes" description="Call history dispositions">{!stats || !Object.keys(stats.outcomes || {}).length ? <EmptyState title="No outcomes yet" description="Call outcomes will be summarized here." /> : <div className="grid grid-cols-2 gap-3 p-5">{Object.entries(stats.outcomes).sort((a, b) => b[1] - a[1]).map(([outcome, count]) => <div key={outcome} className="rounded-lg bg-muted/50 p-4"><StatusBadge value={outcome} /><p className="mt-3 text-2xl font-semibold">{count}</p></div>)}</div>}</SectionCard></div>
        <SectionCard title="Campaign comparison"><div className="overflow-x-auto"><table className="w-full text-left text-sm"><thead className="bg-muted/50 text-xs text-muted-foreground"><tr>{['Campaign', 'Calls', 'Answered', 'Qualified', 'Transfers', 'Status'].map(h => <th key={h} className="px-5 py-3 font-medium">{h}</th>)}</tr></thead><tbody className="divide-y divide-border">{campaigns.map(({ campaign, stats: campaignStats, leads }) => <tr key={campaign.id}><td className="px-5 py-4 font-medium">{campaign.name}</td><td className="px-5 py-4">{sumValues(campaignStats.attempt_outcomes)}</td><td className="px-5 py-4">{leads.filter(isAnswered).length}</td><td className="px-5 py-4">{leads.filter(isQualified).length}</td><td className="px-5 py-4">{leads.filter(l => Boolean(l.last_transfer_successful)).length}</td><td className="px-5 py-4"><StatusBadge value={campaign.status} /></td></tr>)}</tbody></table>{!campaigns.length && <EmptyState title="No campaigns" description="Campaign comparisons appear once campaigns exist." />}</div></SectionCard>
        <div className="grid gap-4 md:grid-cols-2"><MetricCard label="Average call duration" value={`${Math.round(stats?.avg_duration_seconds || 0)}s`} detail="Across call history" icon={Clock3} /><SectionCard title="Qualification failure reasons"><EmptyState title="Not exposed as an aggregate" description="Lead-level failed rules are available, but the current API does not provide a complete paginated aggregate. No synthetic ranking is shown." /></SectionCard></div>
    </div>;
}
