/* eslint-disable @typescript-eslint/no-explicit-any */
import { ChangeEvent, useEffect, useState } from 'react';
import axios from 'axios';
import { FileText, Plus, Search, Trash2, Upload } from 'lucide-react';
import { toast } from 'sonner';
import { EmptyState, PageHeader, PageLoading, SectionCard, inputClass, primaryButton, secondaryButton } from '../components/operations/ProductUI';
import { Campaign, KnowledgeDocument, getCampaigns, getKnowledgeDocuments } from '../services/operationsApi';

export default function KnowledgeBasePage() {
    const [campaigns, setCampaigns] = useState<Campaign[]>([]); const [campaignId, setCampaignId] = useState(''); const [docs, setDocs] = useState<KnowledgeDocument[]>([]); const [loading, setLoading] = useState(true); const [adding, setAdding] = useState(false); const [name, setName] = useState(''); const [content, setContent] = useState(''); const [error, setError] = useState('');
    const refresh = async (id: string) => { if (!id) { setDocs([]); return; } setDocs(await getKnowledgeDocuments(id)); };
    useEffect(() => { (async () => { try { const rows = await getCampaigns(); setCampaigns(rows); const id = rows[0]?.id || ''; setCampaignId(id); await refresh(id); } catch (e: any) { setError(e?.message || 'Unable to load knowledge documents.'); } finally { setLoading(false); } })(); }, []);
    const selectCampaign = async (id: string) => { setCampaignId(id); setLoading(true); try { await refresh(id); } finally { setLoading(false); } };
    const addText = async () => { if (!name.trim() || !content.trim()) return; try { await axios.post(`/api/outbound/campaigns/${campaignId}/knowledge/text`, { name: name.trim(), content, content_type: 'text/plain' }); setName(''); setContent(''); setAdding(false); await refresh(campaignId); toast.success('Knowledge document added'); } catch (e: any) { toast.error(e?.response?.data?.detail || 'Could not add document'); } };
    const upload = async (event: ChangeEvent<HTMLInputElement>) => { const file = event.target.files?.[0]; if (!file) return; const body = new FormData(); body.append('file', file); try { await axios.post(`/api/outbound/campaigns/${campaignId}/knowledge/upload`, body); await refresh(campaignId); toast.success('Document uploaded'); } catch (e: any) { toast.error(e?.response?.data?.detail || 'Upload failed'); } finally { event.target.value = ''; } };
    const remove = async (doc: KnowledgeDocument) => { if (!window.confirm(`Delete “${doc.name}”?`)) return; try { await axios.delete(`/api/outbound/campaigns/${campaignId}/knowledge/${doc.id}`); await refresh(campaignId); toast.success('Document deleted'); } catch { toast.error('Delete failed'); } };
    if (loading && !campaigns.length) return <PageLoading label="Loading knowledge base" />;
    return <div className="space-y-8"><PageHeader eyebrow="AI workspace" title="Knowledge Base" description="Campaign-scoped product facts, FAQs, pricing, and objection-handling material used by live agents." actions={<div className="flex gap-2"><label className={`${secondaryButton} cursor-pointer`}><Upload className="h-4 w-4" /> Upload document<input type="file" accept=".txt,.md,.markdown,.pdf" className="sr-only" disabled={!campaignId} onChange={upload} /></label><button className={primaryButton} disabled={!campaignId} onClick={() => setAdding(true)}><Plus className="h-4 w-4" /> Add text</button></div>} />
        {error && <div className="rounded-lg border border-red-500/20 bg-red-500/10 p-4 text-sm text-red-700">{error}</div>}
        <div className="max-w-sm"><label className="mb-2 block text-xs font-semibold uppercase tracking-wider text-muted-foreground">Campaign</label><select className={inputClass} value={campaignId} onChange={e => selectCampaign(e.target.value)}><option value="">Select campaign</option>{campaigns.map(c => <option key={c.id} value={c.id}>{c.name}</option>)}</select></div>
        {adding && <SectionCard title="Add text knowledge" description="Content is chunked and indexed by the existing campaign KB store."><div className="space-y-4 p-5"><div><label className="mb-2 block text-sm font-medium">Title</label><input className={inputClass} value={name} onChange={e => setName(e.target.value)} placeholder="Pricing and plans" /></div><div><label className="mb-2 block text-sm font-medium">Content</label><textarea className={`${inputClass} h-52 resize-y py-3 leading-6`} value={content} onChange={e => setContent(e.target.value)} placeholder="Add factual content the agent may use…" /></div><div className="flex justify-end gap-2"><button className={secondaryButton} onClick={() => setAdding(false)}>Cancel</button><button className={primaryButton} onClick={addText} disabled={!name.trim() || !content.trim()}>Save document</button></div></div></SectionCard>}
        <SectionCard title="Documents" description={`${docs.length} document${docs.length === 1 ? '' : 's'} in the selected campaign`}>
            {!campaignId ? <EmptyState title="Select a campaign" description="Knowledge is stored and retrieved within a campaign scope." /> : !docs.length ? <EmptyState title="No knowledge documents" description="Add text or upload TXT, Markdown, or PDF content supported by the existing backend." /> : <div className="overflow-x-auto"><table className="w-full text-left text-sm"><thead className="bg-muted/50 text-xs text-muted-foreground"><tr>{['Title', 'Type', 'Size', 'Chunks', 'Added', ''].map(h => <th key={h} className="px-5 py-3 font-medium">{h}</th>)}</tr></thead><tbody className="divide-y divide-border">{docs.map(doc => <tr key={doc.id}><td className="px-5 py-4"><span className="flex items-center gap-2 font-medium"><FileText className="h-4 w-4 text-primary" />{doc.name}</span></td><td className="px-5 py-4 text-muted-foreground">{doc.content_type}</td><td className="px-5 py-4">{doc.character_count.toLocaleString()} chars</td><td className="px-5 py-4">{doc.chunk_count}</td><td className="px-5 py-4 text-muted-foreground">{new Date(doc.created_at_utc).toLocaleDateString()}</td><td className="px-5 py-4 text-right"><button onClick={() => remove(doc)} title="Delete document" className="rounded-md p-2 text-muted-foreground hover:bg-red-500/10 hover:text-red-600"><Trash2 className="h-4 w-4" /></button></td></tr>)}</tbody></table></div>}
        </SectionCard>
        <SectionCard title="Test Knowledge Base" description="Ask a question and inspect campaign-scoped retrieval results."><div className="p-5"><div className="flex gap-2"><div className="relative flex-1"><Search className="absolute left-3 top-2.5 h-4 w-4 text-muted-foreground" /><input disabled className={`${inputClass} pl-9`} placeholder="Search endpoint not available in the admin API" /></div><button disabled className={primaryButton}>Search</button></div><p className="mt-3 text-xs leading-5 text-muted-foreground">Live agents can use campaign KB search, but the current admin API does not expose a safe test-search endpoint. No result is simulated here.</p></div></SectionCard>
    </div>;
}
