/* eslint-disable @typescript-eslint/no-explicit-any */
import { useEffect, useMemo, useState } from 'react';
import { ExternalLink, Search, X } from 'lucide-react';
import { Link } from 'react-router-dom';
import { EmptyState, PageHeader, PageLoading, SectionCard, StatusBadge, inputClass, secondaryButton } from '../components/operations/ProductUI';
import { Lead, getCampaignLeads, getCampaigns, isQualified } from '../services/operationsApi';

const fmt = (v?: string | null) => v ? new Date(v).toLocaleString([], { dateStyle: 'medium', timeStyle: 'short' }) : '—';
const yesNo = (v: unknown) => typeof v === 'boolean' ? (v ? 'Yes' : 'No') : String(v ?? '—');
export default function LeadsPage() {
    const [leads, setLeads] = useState<Lead[]>([]); const [loading, setLoading] = useState(true); const [error, setError] = useState(''); const [query, setQuery] = useState(''); const [selected, setSelected] = useState<Lead | null>(null);
    useEffect(() => { (async () => { try { const campaigns = await getCampaigns(); setLeads((await Promise.all(campaigns.map(c => getCampaignLeads(c)))).flat()); } catch (e: any) { setError(e?.message || 'Unable to load leads.'); } finally { setLoading(false); } })(); }, []);
    const filtered = useMemo(() => leads.filter(l => [l.name, l.phone_number, l.campaign_name, l.custom_vars?.company].some(v => String(v || '').toLowerCase().includes(query.toLowerCase()))), [leads, query]);
    if (loading) return <PageLoading label="Loading leads" />;
    return <div className="space-y-8"><PageHeader eyebrow="Outbound" title="Leads" description="Qualification, outcomes, callbacks, and consent status across every campaign." />
        {error && <div className="rounded-lg border border-red-500/20 bg-red-500/10 p-4 text-sm text-red-700">{error}</div>}
        <SectionCard action={<div className="relative w-72"><Search className="absolute left-3 top-2.5 h-4 w-4 text-muted-foreground" /><input className={`${inputClass} pl-9`} placeholder="Search name, phone, company…" value={query} onChange={e => setQuery(e.target.value)} /></div>}>
            {!filtered.length ? <EmptyState title="No leads found" description={leads.length ? 'Try a different search.' : 'Leads will appear after they are added to a campaign.'} /> : <div className="overflow-x-auto"><table className="w-full min-w-[1050px] text-left text-sm"><thead className="bg-muted/50 text-xs text-muted-foreground"><tr>{['Name', 'Phone', 'Company', 'Campaign', 'State', 'Qualification', 'Last outcome', 'Last call', 'Callback', 'DNC'].map(h => <th key={h} className="px-5 py-3 font-medium">{h}</th>)}</tr></thead><tbody className="divide-y divide-border">{filtered.map(lead => <tr key={lead.id} onClick={() => setSelected(lead)} className="cursor-pointer hover:bg-muted/30"><td className="px-5 py-4 font-medium">{lead.name || 'Unnamed lead'}</td><td className="px-5 py-4 tabular-nums">{lead.phone_number}</td><td className="px-5 py-4">{lead.custom_vars?.company || '—'}</td><td className="px-5 py-4">{lead.campaign_name}</td><td className="px-5 py-4"><StatusBadge value={lead.state} /></td><td className="px-5 py-4"><StatusBadge value={isQualified(lead) ? 'qualified' : lead.qualification_result ? 'not qualified' : 'pending'} /></td><td className="px-5 py-4">{lead.last_outcome ? <StatusBadge value={lead.last_outcome} /> : '—'}</td><td className="px-5 py-4 text-muted-foreground">{fmt(lead.last_attempt_at_utc || lead.last_started_at_utc)}</td><td className="px-5 py-4">{fmt(lead.callback_at_utc)}</td><td className="px-5 py-4">{lead.do_not_call_at_utc ? <StatusBadge value="do_not_call" label="Yes" /> : 'No'}</td></tr>)}</tbody></table></div>}
        </SectionCard>
        {selected && <div className="fixed inset-0 z-40 flex justify-end bg-black/30" onClick={() => setSelected(null)}><aside className="h-full w-full max-w-xl overflow-y-auto bg-card p-6 shadow-2xl" onClick={e => e.stopPropagation()}><div className="flex items-start justify-between"><div><p className="text-xs font-semibold uppercase tracking-wider text-primary">Lead detail</p><h2 className="mt-2 text-2xl font-semibold">{selected.name || selected.phone_number}</h2><p className="mt-1 text-sm text-muted-foreground">{selected.custom_vars?.company || 'No company'} · {selected.campaign_name}</p></div><button onClick={() => setSelected(null)} className="rounded-md p-2 hover:bg-accent"><X className="h-5 w-5" /></button></div>
            <div className="mt-6 space-y-5"><SectionCard title="Lead information"><dl className="grid grid-cols-2 gap-4 p-5 text-sm"><div><dt className="text-muted-foreground">Phone</dt><dd className="mt-1 font-medium">{selected.phone_number}</dd></div><div><dt className="text-muted-foreground">State</dt><dd className="mt-1"><StatusBadge value={selected.state} /></dd></div><div><dt className="text-muted-foreground">Attempts</dt><dd className="mt-1 font-medium">{selected.attempt_count}</dd></div><div><dt className="text-muted-foreground">Last outcome</dt><dd className="mt-1">{selected.last_outcome || '—'}</dd></div></dl></SectionCard>
            <SectionCard title="Qualification" action={<StatusBadge value={isQualified(selected) ? 'qualified' : selected.qualification_result ? 'not qualified' : 'pending'} />}><div className="p-5"><p className="mb-4 text-3xl font-semibold">{selected.qualification_score ?? selected.qualification_result?.score ?? 0}%</p><dl className="grid grid-cols-2 gap-x-6 gap-y-4 text-sm">{Object.entries(selected.qualification_state || {}).map(([key, value]) => <div key={key}><dt className="capitalize text-muted-foreground">{key.replace(/_/g, ' ')}</dt><dd className="mt-1 font-medium">{yesNo(value)}</dd></div>)}</dl>{Array.isArray(selected.qualification_result?.failed_rules) && selected.qualification_result.failed_rules.length > 0 && <div className="mt-5 rounded-md bg-red-500/10 p-3 text-sm text-red-700"><p className="font-semibold">Failed rules</p><ul className="mt-2 list-disc pl-4">{selected.qualification_result.failed_rules.map((r: any, i: number) => <li key={i}>{typeof r === 'string' ? r : r.reason || r.field}</li>)}</ul></div>}</div></SectionCard>
            <SectionCard title="Follow-up & consent"><dl className="grid grid-cols-2 gap-4 p-5 text-sm"><div><dt className="text-muted-foreground">Callback</dt><dd className="mt-1 font-medium">{fmt(selected.callback_at_utc)}</dd></div><div><dt className="text-muted-foreground">Do not call</dt><dd className="mt-1 font-medium">{selected.do_not_call_at_utc ? `Yes · ${fmt(selected.do_not_call_at_utc)}` : 'No'}</dd></div></dl></SectionCard>
            {selected.last_summary && <SectionCard title="Latest summary"><p className="p-5 text-sm leading-6 text-muted-foreground">{selected.last_summary}</p></SectionCard>}
            {selected.last_call_history_call_id && <Link to={`/calls?id=${encodeURIComponent(selected.last_call_history_call_id)}`} className={secondaryButton}>Open call review <ExternalLink className="h-4 w-4" /></Link>}
            </div></aside></div>}
    </div>;
}
